import { Text } from "@/components/UI";
import { SocialIcon } from "react-social-icons";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface ILayout {
  path: string;
  children: React.ReactNode;
}

export default function RootLayout({ children }: ILayout) {
  return (
    <div className="flex flex-col md:flex-row w-screen h-max flex-col-reverse">
      {/* left section  */}
      <div className="md:w-1/2 bg-buttonSecondary md:-translate-x-12 md:-skew-x-6">
        {/* logo */}
        <div className="p-12 text-white font-bold md:translate-x-12 md:skew-x-6">
          <Text variant="titleXl" className="max-w-max">
            LOGO
          </Text>
          <div className="flex  justify-center items-center mt-60">
            <Text variant="titleXl" className="max-w-max font-bold text-6xl">
              BOARD.
            </Text>
          </div>
          <div className="flex gap-x-8 mt-60 justify-center">
            <SocialIcon bgColor="#fff" url="https://github.com/deepak-singh5219" />
            <SocialIcon bgColor="#fff" url="https://twitter.com/techydeepak7" />
            <SocialIcon bgColor="#fff" url="https://www.linkedin.com/in/deepaksingh5219" />
            <SocialIcon bgColor="#fff" url="https://www.discord.com/devdeepak" />
          </div>
        </div>
      </div>
      <div className="bg-primary md:w-1/2">
        <div className="flex items-center justify-center h-screen">
          {children}
        </div>
      </div>
    </div>
  );
}
