export { default as ArticleIcon } from "./ArticleIcon";
export { default as HomeIcon } from "./HomeIcon";
export { default as UsersIcon } from "./UsersIcon";
export { default as VideosIcon } from "./VideosIcon";
export { default as CollapsIcon } from "./CollapsIcon";
export { default as LogoIcon } from "./Logo";
export { default as LogoutIcon } from "./LogoutIcon";
export { default as Dashboard } from "./Dashboard";
export { default as Transactions } from "./Transactions";
export { default as Settings } from "./Settings";
export { default as Users } from "./Users";
export { default as Schedules } from "./Schedules";
export { default as GoogleIcon } from "./google-icon";
export { default as Icon1 } from "./icon1"
export { default as Icon2 } from "./Icon2"
export { default as Icon3 } from "./Icon3"
export { default as Icon4 } from "./Icon4"
export { default as Whatsapp } from "./Whatsapp"
export { default as Youtube } from "./Youtube"
export { default as Instagram } from "./Instagram"
export { default as Email } from "./Email"

